version: "3"
services:
  app:
    container_name: express-mongo
    restart: always
    build: ./
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    links:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
